#pragma once

// clang-format off
#define _FLUX_JOIN(A, B) A##B
#define  FLUX_JOIN(A, B) _FLUX_JOIN(A, B)

#define FLUX_UNIQUE_NAME(BASE) FLUX_JOIN(BASE, __COUNTER__)

#define _FLUX_TO_STRING(X) #X
#define  FLUX_TO_STRING(X) _FLUX_TO_STRING(X)

#define FLUX_EVAL(...) __VA_ARGS__
#define FLUX_HEAD(X, ...) X
#define FLUX_TAIL(X, ...) __VA_ARGS__

#define  FLUX_VARCOUNT(...) FLUX_EVAL(_FLUX_VARCOUNT(__VA_ARGS__, 9, 8, 7, 6, 5, 4, 3, 2, 1,))
#define _FLUX_VARCOUNT(_, _9, _8, _7, _6, _5, _4, _3, _2, X_,...) X_

#define FLUX_TRANSFORM(FUNC, ...) FLUX_JOIN(FLUX_TRANSFORM_,FLUX_VARCOUNT(__VA_ARGS__))(FUNC,__VA_ARGS__)
#define FLUX_TRANSFORM_1(FUNC, ...) FUNC(__VA_ARGS__)
#define FLUX_TRANSFORM_2(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_1(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_3(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_2(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_4(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_3(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_5(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_4(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_6(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_5(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_7(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_6(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_8(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_7(FUNC, FLUX_TAIL(__VA_ARGS__))
#define FLUX_TRANSFORM_9(FUNC, ...) FUNC(FLUX_HEAD(__VA_ARGS__)), FLUX_TRANSFORM_8(FUNC, FLUX_TAIL(__VA_ARGS__))
// clang-format on