name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest]
        compiler:
          - { cc: clang, cxx: 'clang++' }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          envFilePath: ./.github/variables/versions.env

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -U Jinja2

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}
          ninjaVersion: ${{ env.NINJA_VERSION }}

      - name: Install Clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${{ env.COMPILER_VERSION }} main"
          sudo apt update
          sudo apt install -y ${{ matrix.compiler.cc }}-${{ env.COMPILER_VERSION }} libc++-${{ env.COMPILER_VERSION }}-dev libc++abi-${{ env.COMPILER_VERSION }}-dev

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev
          sudo apt install libgl-dev

      - name: Configure
        env:
          CC: ${{ matrix.compiler.cc }}-${{ env.COMPILER_VERSION }}
          CXX: ${{ matrix.compiler.cxx }}-${{ env.COMPILER_VERSION }}
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DFLUX_GRAPHICS_API=OpenGL -B ${{ github.workspace }}/build/${{ matrix.os }}-${{ env.BUILD_TYPE }} -G Ninja

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{ github.workspace }}/build/${{ matrix.os }}-${{ env.BUILD_TYPE }} --config ${{ env.BUILD_TYPE }}

  windows:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:      
        os: [windows-latest]
        compiler:
          - { cc: clang, cxx: 'clang++', version: 18 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install -U Jinja2

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latestrc # use the latest release candidate
          ninjaVersion: latest   # use the latest release

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{ matrix.compiler.version }}

      - name: Configure
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DFLUX_GRAPHICS_API=OpenGL -B ${{ github.workspace }}/build/${{ matrix.os }}-${{ env.BUILD_TYPE }} -G Ninja

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{ github.workspace }}/build/${{ matrix.os }}-${{ env.BUILD_TYPE }} --config ${{ env.BUILD_TYPE }}
