name: linter

on:
  push:
    branches: [ "master" ]
    paths: ['**.cpp', '**.hpp', '**.inl']
  pull_request:
    branches: [ "master" ]
    paths: ['**.cpp', '**.hpp', '**.inl']

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'     # Use .clang-format config file. 
          tidy-checks: '-*' # Disable clang-tidy checks. 
          # Only 'update' a single comment in a pull request's thread. 
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast?!
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: exit 1